In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt5
import seaborn as sns

In [2]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
df = pd.read_csv('Fertilizer2.csv')

In [7]:
df

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0            26         52        38     Sandy      Maize        37   
1            29         52        45     Loamy  Sugarcane        12   
2            34         65        62     Black     Cotton         7   
3            32         62        34       Red    Tobacco        22   
4            28         54        46    Clayey      Paddy        35   
..          ...        ...       ...       ...        ...       ...   
94           25         50        32    Clayey     Pulses        24   
95           30         60        27       Red    Tobacco         4   
96           38         72        51     Loamy      Wheat        39   
97           36         60        43     Sandy    Millets        15   
98           29         58        57     Black  Sugarcane        12   

    Potassium  Phosphorous Fertilizer Name  
0           0            0            Urea  
1           0           36             DAP  
2           9           30        14-35-14  
3           0           20           28-28  
4           0            0            Urea  
..        ...          ...             ...  
94          0           19           28-28  
95         17           17        10-26-26  
96          0            0            Urea  
97          0           41             DAP  
98          0           10           20-20  

[99 rows x 9 columns]

In [15]:
df.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [16]:
df.isna()

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0         False      False     False      False      False     False   
1         False      False     False      False      False     False   
2         False      False     False      False      False     False   
3         False      False     False      False      False     False   
4         False      False     False      False      False     False   
..          ...        ...       ...        ...        ...       ...   
94        False      False     False      False      False     False   
95        False      False     False      False      False     False   
96        False      False     False      False      False     False   
97        False      False     False      False      False     False   
98        False      False     False      False      False     False   

    Potassium  Phosphorous  Fertilizer Name  
0       False        False            False  
1       False        False            False  
2       False        False            False  
3       False        False            False  
4       False        False            False  
..        ...          ...              ...  
94      False        False            False  
95      False        False            False  
96      False        False            False  
97      False        False            False  
98      False        False            False  

[99 rows x 9 columns]

In [17]:
df.isna().sum()

Temparature        0
Humidity           0
Moisture           0
Soil Type          0
Crop Type          0
Nitrogen           0
Potassium          0
Phosphorous        0
Fertilizer Name    0
dtype: int64

In [18]:
df.head(3)

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14

In [19]:
df['Fertilizer Name'].unique()

array(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20',
       '10-26-26'], dtype=object)

In [21]:
#df['Fertilizer']

In [23]:
df['Soil Type'].unique()

array(['Sandy', 'Loamy', 'Black', 'Red', 'Clayey'], dtype=object)

In [24]:
#df['Soil']

In [25]:
df['Crop Type'].unique()

array(['Maize', 'Sugarcane', 'Cotton', 'Tobacco', 'Paddy', 'Barley',
       'Wheat', 'Millets', 'Oil seeds', 'Pulses', 'Ground Nuts'],
      dtype=object)

In [16]:
#df['Crop']

In [17]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# df['Soil'] = le.fit_transform(df['Soil'])

In [18]:
#df['Soil']

In [19]:
#df['Crop'] = le.fit_transform(df['Crop'])

In [20]:
#df['Crop']




In [26]:
Fert_dict = {'Urea':3, 'DAP':4, '14-35-14':5, '28-28':6, '17-17-17':7, '20-20':8,
       '10-26-26':9}

In [27]:
df['Fertilizer Name'] = df['Fertilizer Name'].map(Fert_dict)

In [28]:
df['Fertilizer Name']

0     3
1     4
2     5
3     6
4     3
     ..
94    6
95    9
96    3
97    4
98    8
Name: Fertilizer Name, Length: 99, dtype: int64

In [29]:
Soil_dict = {'Clayey' : 1, 'Sandy' : 4,  'Loamy' : 6, 'Black':8, 'Red':9}

In [30]:
df['Soil Type'] = df['Soil Type'].map(Soil_dict)

In [31]:
df['Soil Type'].unique()

array([4, 6, 8, 9, 1])

In [32]:
df['Soil Type']

0     4
1     6
2     8
3     9
4     1
     ..
94    1
95    9
96    6
97    4
98    8
Name: Soil Type, Length: 99, dtype: int64

In [34]:
df['Crop Type'].unique()

array(['Maize', 'Sugarcane', 'Cotton', 'Tobacco', 'Paddy', 'Barley',
       'Wheat', 'Millets', 'Oil seeds', 'Pulses', 'Ground Nuts'],
      dtype=object)

In [35]:
Crop_dict = {'Maize':3, 'Sugarcane':4, 'Cotton':5, 'Tobacco':6, 'Paddy':7, 'Barley':8,
       'Wheat':9, 'Millets':10, 'Oil seeds':11, 'Pulses':12, 'Ground Nuts':13}

In [36]:
df['Crop Type'] = df['Crop Type'].map(Crop_dict)

In [37]:
df['Crop Type']

0      3
1      4
2      5
3      6
4      7
      ..
94    12
95     6
96     9
97    10
98     4
Name: Crop Type, Length: 99, dtype: int64

In [38]:
df.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [39]:
x = df[['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous']]

y = df ['Fertilizer Name']

In [40]:
x.head(3)

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0           26         52        38          4          3        37   
1           29         52        45          6          4        12   
2           34         65        62          8          5         7   

   Potassium  Phosphorous  
0          0            0  
1          0           36  
2          9           30

In [64]:
y.head(3)

0    3
1    4
2    5
Name: Fertilizer Name, dtype: int64

In [66]:
y.unique()

array([3, 4, 5, 6, 7, 8, 9])

In [41]:
xtr,xte,ytr,yte = train_test_split(x,y,train_size=0.80,random_state=12345)

In [42]:
print("xtrin: ",xtr.shape)
print("ytrin: ",ytr.shape)
print("xtest: ",xte.shape)
print("ytest: ",yte.shape)

xtrin:  (79, 8)
ytrin:  (79,)
xtest:  (20, 8)
ytest:  (20,)


In [43]:
log_model = LogisticRegressionCV()
log_model.fit(xtr,ytr)

LogisticRegressionCV()

In [44]:
ypred1 = log_model.predict(xte)

In [45]:
accuracy_score(yte,ypred1)

1.0

In [46]:
def build_log():
    from sklearn.linear_model import LogisticRegression
    model = LogisticRegression()
    model.fit(xtr,ytr)
    return model

In [47]:
def build_knn():
    model = KNeighborsClassifier()
    model.fit(xtr,ytr)
    return model

In [48]:
def build_Dtree():
    model = DecisionTreeClassifier()
    model.fit(xtr,ytr)
    return model

In [49]:
def build_rand():
    model = RandomForestClassifier()
    model.fit(xtr,ytr)
    return model

In [50]:
def build_gb():
    model = GradientBoostingClassifier()
    model.fit(xtr,ytr)
    return model

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ytr = le.fit_transform(ytr) 
yte = le.fit_transform(yte)
def build_xgb():
    model = XGBClassifier(n_estimators = 200,learning_rate = 0.1,verbose = False)
    model.fit(xtr,ytr)
    return model

In [52]:
# def Evaluate_models(model):
#     ypred = model.predict(xte)
#     accuracy = accuracy_score(yte,ypred)
#     f1 = f1_score(yte,ypred)
#     precision = precision_score(yte,ypred)
#     recall = recall_score(yte,ypred)
#     return accuracy,f1,precision,recall


from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
def evaluate_model(model):
    # define y_true and y_pred
    y_true = yte
    y_pred = model.predict(xte)
    cm = confusion_matrix(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred,average='macro')
    # precision_score(yte,ypred,average='macro')
    recall = recall_score(y_true, y_pred,average='macro')
    f1 = f1_score(y_true, y_pred,average='macro')

    return accuracy, precision, recall, f1

In [53]:
# d = ["Logistic Regression","KNN","Decision Tree","Random Forest","XGBoost"] 
# # algorithms = {'functions':Logistic Regression,"KNN","Decision Tree","Random Forest","XGBoost"}
# algo = [build_log(),build_knn(),build_Dtree(),build_rand(),build_xgb()]

# df_new = pd.DataFrame(d,columns =['names'])
# df_new['algorithms'] = algorithms

In [54]:
# df_new

In [55]:
# build_log()

In [56]:
# model_func[0]['func']()

In [57]:
# create a list of functions
model_functions = [
    {"name": "Logistic", "function": build_log}, 
    {"name": "KNN", "function": build_knn},
    {"name": "Decision Tree", "function": build_Dtree},
     {"name": "Random Forest", "function": build_rand},
     {"name": "GBoost", "function": build_gb},
     {"name": "XGBoost", "function": build_xgb}
    
]

# empty list to collect the modelwise report
model_evaluation_report = []

# iterate over the list, create model and evaluate the model
for model_info in model_functions:
    model = model_info["function"]()
    metrics = evaluate_model(model)
    model_evaluation_report.append({
        "name": model_info["name"],
        "accuracy": metrics[0],
        # "precision": metrics[1], 
        "recall": metrics[2],
        "f1": metrics[3]
    })

# create a data frame of the result
df_result = pd.DataFrame(model_evaluation_report)
df_result

name  accuracy    recall        f1
0       Logistic      1.00  1.000000  1.000000
1            KNN      0.80  0.800000  0.714286
2  Decision Tree      0.95  0.928571  0.904762
3  Random Forest      1.00  1.000000  1.000000
4         GBoost      0.95  0.928571  0.904762
5        XGBoost      1.00  1.000000  1.000000

In [51]:
# Fert_dict = {'DAP and MOP' : 1, 'Good NPK' :2, 'MOP':3, 'Urea and DAP':4, 'Urea and MOP':5,
#        'Urea ':6, 'DAP':7}

In [52]:
# def result():
#     T = int(input("enter Temperature:"))
#     H = int(input("enter Humidity:"))
#     M = int(input("enter Moisture:"))
#     SOIL_TYPE = float(input("enter Soil type:"))
#     CROP_TYPE = float(input("enter Crop Type:"))
#     N = float(input("enter Sodium:"))
#     K = float(input("enter Potassium:"))
#     P = float(input("enter Phosphorous:"))
    
#     output = model.predict([[T,H,M,SOIL_TYPE,N,K,P]])
   
    
#     for i in d.values():
#         if(output == i):
#             keys = [k for k, i in d.items() if i == output]
#     return ("Recommended crop is : ",keys[0].upper())


In [58]:
# result()

In [59]:
df.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [ ]:
# def result():
#     T = int(input("enter Temperature:"))
#     H = int(input("enter Humidity:"))
#     R = int(input("enter Rainfall:"))
#     pH = float(input("enter pH:"))
#     N = float(input("enter N:"))
#     P= float(input("enter P:"))
#     K = float(input("enter K:"))
#     Soil = int(input("enter soil:"))
#     Crop = int(input("enter crop"))
    
#     output = model.predict([[T,H,R,pH,N,P,K,Soil,Crop]])
   
    
#     for i in Fert_dict.values():
#         if(output == i):
#             keys = [k for k, i in Fert_dict.items() if i == output]
#     return ("Recommended fertilizer : ",keys[0].upper())


In [60]:
# result()

In [61]:
model = KNeighborsClassifier()
model.fit(xtr,ytr)

KNeighborsClassifier()

In [ ]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression

In [63]:
ypred = model.predict(xte)

In [68]:
# model.predict([[29	,52,45,	6,	7	,12	,20	,36]])

array([2])

In [ ]:
import pickle
with open('./Reccommendation_try.pkl', 'wb') as file:
    pickle.dump(model, file)